### ISSUE TITLE
Config for batch execution

### ISSUE THREAD

**Issue by ahstn** [ahstn/karetaker#11]
New command and config handling for executing all existing functionality.

Rough idea:
```yaml
global:
  allowlist: istio, pre-release

namespaces:
- name: auth
  allowlist:
  - develop
  age:
    resources:
    - deployments
    - services
    duration: 168h # 7 days
  unused:
    resources:
    - configmaps 
    - secrets
    - jobs
```
